name: musicly
description: "Find your favorite music and enjoy it!"
version: 1.0.0+1

environment:
  sdk: ">=3.4.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  lottie: ^3.1.2
  google_sign_in: ^6.2.1
  firebase_core: ^3.1.0
  firebase_auth: ^5.1.0
  connectivity_plus: ^6.0.3
  get: ^4.6.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/animation/animation.json
    - assets/images/login_screen.png
    - assets/images/google_logo.png
  fonts:
    - family: SourceSansPro
      fonts:
        - asset: assets/fonts/SourceSansPro-Regular.ttf
        - asset: assets/fonts/SourceSansPro-BlackItalic.ttf
        - asset: assets/fonts/SourceSansPro-BoldItalic.ttf
        - asset: assets/fonts/SourceSansPro-Italic.ttf
        - asset: assets/fonts/SourceSansPro-ExtraLightItalic.ttf
        - asset: assets/fonts/SourceSansPro-LightItalic.ttf
        - asset: assets/fonts/SourceSansPro-SemiBoldItalic.ttf
        - asset: assets/fonts/SourceSansPro-Black.ttf
        - asset: assets/fonts/SourceSansPro-Bold.ttf
        - asset: assets/fonts/SourceSansPro-ExtraLight.ttf
        - asset: assets/fonts/SourceSansPro-Light.ttf
        - asset: assets/fonts/SourceSansPro-SemiBold.ttf
